defaults:
  - surge_4
  - _self_

synth:
  plugin_path: surgepy
  plugin_state_path: presets/surge-mini.fxp
renderer_backend: surgepy
renderer_version: 1.3.master.f7b97c68
plugin_reload_cadence: render
gui_toggle_cadence: never
