_target_: pytorch_lightning.trainer.Trainer

default_root_dir: ${paths.output_dir}

log_every_n_steps: 100
val_check_interval: 10_000
gradient_clip_val: 1.0

accelerator: cpu
devices: 1

# mixed precision for extra speed-up
# precision: 16

# perform a validation loop every N training epochs
check_val_every_n_epoch: null

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False
