
help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

format: ## Run pre-commit hooks
	pre-commit run -a

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

setup-rclone: ## Configure rclone for Cloudflare R2 (requires .env sourced)
	bash scripts/setup-rclone.sh

test: ## Run not slow tests
	pytest -k "not slow"

test-full: ## Run all tests
	pytest

train: ## Train the model
	python src/train.py

# =====================================================================
# Docker targets
# =====================================================================
#
# ⚠️  SECURITY: All images produced by this Makefile contain baked Cloudflare
#     R2 credentials (rclone config). Push ONLY to a PRIVATE registry.
#     Anyone who can pull the image has read/write access to the R2 bucket.
#     See README for future hardening steps.
#
# Two build modes:
#   1. docker-build-dev-snapshot — self-contained image. Clones repo at GIT_REF,
#                                  bakes source + deps + Surge XT + rclone/R2 config.
#                                  Run it anywhere (CI, cloud, vast.ai).
#
#   2. docker-build-dev-live     — DEV image. Same base (Surge + deps + R2 config)
#                                  but does NOT bake source code. Mount your local
#                                  working tree at runtime with docker-run-dev.
#                                  Rebuild only when deps or Surge version change.
#
# Required variables (pass on the command line):
#   GIT_PAT             GitHub personal access token with repo read access.
#                       Required because ktinubu/synth-permutations is private.
#   GIT_REF             Commit SHA, tag, or branch to bake. Prefer full SHA.
#   R2_ACCESS_KEY_ID    Cloudflare R2 API token access key.
#   R2_SECRET_ACCESS_KEY Cloudflare R2 API token secret.
#   R2_ENDPOINT         R2 S3-compatible endpoint URL
#                       (e.g. https://<accountid>.r2.cloudflarestorage.com).
#   R2_BUCKET           R2 bucket name. Baked as an ENV var into the image.
#
# Optional overrides:
#   DOCKER_FILE         Path to Dockerfile          (default: docker/ubuntu22_04/Dockerfile)
#   DOCKER_IMAGE        Image name                  (default: tinaudio/perm)
#   DOCKER_BASE_IMAGE   Base Docker image            (default: vastai cuda base)
#   DOCKER_BUILD_MODE   "source" or "prebuilt"       (default: prebuilt)
#   DOCKER_TARGETPLATFORM   "linux/amd64" or "linux/arm64"           (default: linux/amd64)
#   DOCKER_TORCH_IDX    PyTorch wheel index URL      (default: cu128 wheels)
#   DOCKER_BUILD_FLAGS  Extra flags passed verbatim to docker buildx build.
#   IMAGE_TAG           Tag to use for docker-run-* and docker-ci-* targets (default: dev)
#                       e.g. IMAGE_TAG=dev-snapshot-<sha> to run a specific pinned image.
#   IDLE_AFTER          Set to 1 to drop to bash after generate/train completes (default: 0).
#                       Useful for inspection on vast.ai. Not forwarded by docker-ci-* targets.
#
# Quick-start examples:
#   # Self-contained image (for vast.ai)
#   make docker-build-dev-snapshot GIT_REF=<commit-sha> GIT_PAT=<github-pat> \
#     R2_ACCESS_KEY_ID=<key> R2_SECRET_ACCESS_KEY=<secret> \
#     R2_ENDPOINT=https://<account-id>.r2.cloudflarestorage.com R2_BUCKET=<bucket>
#
#   # Dev image (build once, mount source at runtime)
#   make docker-build-dev-live GIT_REF=<commit-sha> GIT_PAT=<github-pat> \
#     R2_ACCESS_KEY_ID=<key> R2_SECRET_ACCESS_KEY=<secret> \
#     R2_ENDPOINT=https://<account-id>.r2.cloudflarestorage.com R2_BUCKET=<bucket>
#
#   # Run dataset generation (MODE=generate by default)
#   make docker-run-generate TRAIN_SAMPLES=50000
#
#   # Download dataset from R2 and train
#   make docker-run-train R2_DATASET_PATH=runs/surge_simple/<sha>
#
#   # Run dev image with local code mounted
#   make docker-run-dev
#
#   # See docs/pipeline.md for full documentation and plug-and-play command examples.
# =====================================================================
DOCKER_FILE       ?= docker/ubuntu22_04/Dockerfile
DOCKER_IMAGE      ?= tinaudio/perm
DOCKER_BASE_IMAGE ?= vastai/base-image:stock-ubuntu22.04-py310
DOCKER_BUILD_MODE ?= prebuilt
DOCKER_TARGETPLATFORM ?= linux/amd64
TARGETARCH ?= amd64
DOCKER_TORCH_IDX  ?= https://download.pytorch.org/whl/cu128
DOCKER_BUILD_FLAGS ?=
DOCKER_RUN_FLAGS ?=
_INTERNAL_BUILD_FLAGS :=
_INTERNAL_RUN_FLAGS :=
APP_PATH          := /home/build/synth-permutations
CURRENT_LOCAL_GIT_REF := $(strip $(shell git rev-parse --short HEAD))
USE_CLOUD_BUILDER ?= 0

# R2 / rclone configuration — passed as BuildKit secrets + build-arg.
# Set these on the command line or export them as environment variables.
R2_ACCESS_KEY_ID     ?=
R2_SECRET_ACCESS_KEY ?=
R2_ENDPOINT          ?=
R2_BUCKET            ?=

# Common R2 secret flags added to every docker buildx build invocation.
# Credentials are injected via BuildKit --secret (never appear in image layers
# or docker history), but the resulting rclone.conf IS stored in the image.
# ⚠️  Keep ALL produced images in a private registry.
DOCKER_R2_SECRETS = \
	--secret id=r2_access_key_id,env=R2_ACCESS_KEY_ID \
	--secret id=r2_secret_access_key,env=R2_SECRET_ACCESS_KEY \
	--secret id=r2_endpoint,env=R2_ENDPOINT \
	--build-arg R2_BUCKET=$(R2_BUCKET)

# TODO(ktinubu): Looking into TARGETARCH failing to set set by buildx
# even when --platform is provided. In the meantime, we set TARGETARCH
# to amd64 as fallback
# Format base image and target platform: (ubuntu:22.04 -> ubuntu__22.04)
DOCKER_BASE_IMAGE_TAG := $(subst /,_,$(subst :,__,$(DOCKER_BASE_IMAGE)))
TARGET_PLATFORM_TAG := $(subst /,_,$(DOCKER_TARGETPLATFORM))
ifeq ($(USE_CLOUD_BUILDER),1)
_INTERNAL_BUILD_FLAGS += \
	--builder cloud-tinaudio-tinaudio-builder \
	--push \
	--cache-from=type=registry,ref=tinaudio/perm:buildcache-$(TARGET_PLATFORM_TAG) \
	--cache-to=type=registry,ref=tinaudio/perm:buildcache-$(TARGET_PLATFORM_TAG),mode=max
endif


docker-build-dev-snapshot: ## Build self-contained image (requires GIT_REF, GIT_PAT, R2_* vars)
	@if [ -z "$(GIT_REF)" ]; then echo "ERROR: GIT_REF is required. Usage: make docker-build-dev-snapshot GIT_REF=<sha> GIT_PAT=<token> R2_ACCESS_KEY_ID=<key> ..."; exit 1; fi
	DOCKER_BUILDKIT=1 docker buildx build \
		-f $(DOCKER_FILE) \
		$(_INTERNAL_BUILD_FLAGS) $(DOCKER_BUILD_FLAGS) \
		--secret id=git_pat,env=GIT_PAT \
		$(DOCKER_R2_SECRETS) \
		--platform $(DOCKER_TARGETPLATFORM) \
		--build-arg IMAGE="dev-snapshot" \
		--build-arg BUILD_MODE=$(DOCKER_BUILD_MODE) \
		--build-arg BASE_IMAGE=$(DOCKER_BASE_IMAGE) \
		--build-arg SYNTH_PERMUTATIONS_GIT_REF=$(GIT_REF) \
		--build-arg TORCH_INDEX_URL=$(DOCKER_TORCH_IDX) \
		--build-arg TARGETARCH=$(TARGETARCH) \
		-t $(DOCKER_IMAGE):$(DOCKER_BASE_IMAGE_TAG)-dev-snapshot-$(GIT_REF) \
		. \
  		-- 2>&1 | tee data/docker_build_log.txt

# Dev image: installs Surge + all Python deps + R2 config but does NOT copy source code.
# Your local repo is mounted at runtime via docker-run-dev.
# The image is tagged with both :dev and :dev-<short-sha> so you can identify
# which commit's dependency manifests were used.
docker-build-dev-live: ## Build dev image (Surge + deps + R2 config, no baked-in source)
	DOCKER_BUILDKIT=1 docker buildx build \
		-f $(DOCKER_FILE) \
		$(_INTERNAL_BUILD_FLAGS) $(DOCKER_BUILD_FLAGS) \
		--secret id=git_pat,env=GIT_PAT \
		$(DOCKER_R2_SECRETS) \
		--platform $(DOCKER_TARGETPLATFORM) \
		--build-arg IMAGE="dev-live" \
		--build-arg BUILD_MODE=$(DOCKER_BUILD_MODE) \
		--build-arg BASE_IMAGE=$(DOCKER_BASE_IMAGE) \
		--build-arg SYNTH_PERMUTATIONS_GIT_REF=$(CURRENT_LOCAL_GIT_REF) \
		--build-arg TARGETARCH=$(TARGETARCH) \
		--build-arg TORCH_INDEX_URL=$(DOCKER_TORCH_IDX) \
		-t $(DOCKER_IMAGE):$(DOCKER_BASE_IMAGE_TAG)-dev-live-$(CURRENT_LOCAL_GIT_REF) \
		-t $(DOCKER_IMAGE):dev \
		. \
  		-- 2>&1 | tee data/docker_build_log.txt

ifeq ($(USE_LOCAL_WORKSPACE),1)
_INTERNAL_RUN_FLAGS += \
	-v "$(PWD):$(APP_PATH)" \
	-w $(APP_PATH) \
	--entrypoint /home/build/synth-permutations/scripts/docker_entrypoint.sh
endif
# Run the dev image with your local working tree mounted.
# Edits to files on your host are reflected immediately inside the container.
# Add --gpus all after docker run to enable GPU access.
docker-run-dev: ## Run dev image with local source mounted (IMAGE_TAG=dev by default)
	docker run --rm -it --init \
		$(_INTERNAL_RUN_FLAGS) $(DOCKER_RUN_FLAGS) \
		$(DOCKER_IMAGE):$(IMAGE_TAG)

# Dataset generation / training defaults (override on the command line)
TRAIN_SAMPLES    ?= 10000
VAL_SAMPLES      ?= 1000
TEST_SAMPLES     ?= 1000
PARAM_SPEC       ?= surge_simple
OUTPUT_DIR       ?= data/surge_simple
# R2_DATASET_PATH: set when using docker-run-train / docker-ci-train
R2_DATASET_PATH  ?=
TRAIN_ARGS       ?= experiment=surge/flow_simple
# finalize-shards defaults
VAL_SHARDS       ?= 1
TEST_SHARDS      ?= 1
R2_PREFIX        ?=
# IMAGE_TAG: tag for docker-run-* and docker-ci-* targets. Default is :dev (built by docker-build-dev-live).
# Override to run a specific pinned image, e.g. IMAGE_TAG=dev-snapshot-<sha>
IMAGE_TAG        ?= dev
# IDLE_AFTER: set to 1 to drop to a bash shell after generate/train completes.
# Useful for post-run inspection on vast.ai. Not forwarded by docker-ci-* targets.
IDLE_AFTER       ?= 0

# ---------------------------------------------------------------------------
# Interactive run targets — for use on vast.ai or local dev with GPU.
# These include -it (TTY) and --gpus all. Use docker-ci-* for CI or scripts.
# ---------------------------------------------------------------------------

docker-run-generate: ## Generate dataset + upload to R2 (MODE=generate, GPU). IDLE_AFTER=1 to stay in bash.
	docker run --rm -it --gpus all --init \
		$(_INTERNAL_RUN_FLAGS) $(DOCKER_RUN_FLAGS) \
		-e MODE=generate \
		-e PARAM_SPEC=$(PARAM_SPEC) \
		-e TRAIN_SAMPLES=$(TRAIN_SAMPLES) \
		-e VAL_SAMPLES=$(VAL_SAMPLES) \
		-e TEST_SAMPLES=$(TEST_SAMPLES) \
		-e OUTPUT_DIR=$(OUTPUT_DIR) \
		-e IDLE_AFTER=$(IDLE_AFTER) \
		$(DOCKER_IMAGE):$(IMAGE_TAG)

docker-run-train: ## Download dataset from R2 and train (MODE=train, GPU). IDLE_AFTER=1 to stay in bash.
	@if [ -z "$(R2_DATASET_PATH)" ]; then echo "ERROR: R2_DATASET_PATH is required. e.g. make docker-run-train R2_DATASET_PATH=runs/surge_simple/<sha>"; exit 1; fi
	docker run --rm -it --gpus all --init \
		$(_INTERNAL_RUN_FLAGS) $(DOCKER_RUN_FLAGS) \
		-e MODE=train \
		-e PARAM_SPEC=$(PARAM_SPEC) \
		-e R2_DATASET_PATH=$(R2_DATASET_PATH) \
		-e OUTPUT_DIR=$(OUTPUT_DIR) \
		-e TRAIN_ARGS="$(TRAIN_ARGS)" \
		-e IDLE_AFTER=$(IDLE_AFTER) \
		$(DOCKER_IMAGE):$(IMAGE_TAG)

docker-run-finalize: ## Download shards from R2, reshard + stats + upload (MODE=finalize-shards, GPU)
	@if [ -z "$(R2_PREFIX)" ]; then echo "ERROR: R2_PREFIX is required. e.g. make docker-run-finalize R2_PREFIX=runs/surge_simple/batch42"; exit 1; fi
	docker run --rm -it --gpus all --init \
		$(_INTERNAL_RUN_FLAGS) $(DOCKER_RUN_FLAGS) \
		-e MODE=finalize-shards \
		-e R2_PREFIX=$(R2_PREFIX) \
		-e OUTPUT_DIR=$(OUTPUT_DIR) \
		-e VAL_SHARDS=$(VAL_SHARDS) \
		-e TEST_SHARDS=$(TEST_SHARDS) \
		-e IDLE_AFTER=$(IDLE_AFTER) \
		$(DOCKER_IMAGE):$(IMAGE_TAG)

# ---------------------------------------------------------------------------
# CI run targets — identical env vars to docker-run-* but without -it/--gpus.
# Safe for use in CI runners and non-interactive scripts.
# Used by .github/workflows/data-pipeline.yml and for local CI dry-runs.
# ---------------------------------------------------------------------------

docker-ci-generate: ## CI: generate dataset (no TTY, no GPU). Mirror of docker-run-generate for CI/scripts.
	docker run --rm --init \
		$(_INTERNAL_RUN_FLAGS) $(DOCKER_RUN_FLAGS) \
		-e MODE=generate \
		-e PARAM_SPEC=$(PARAM_SPEC) \
		-e TRAIN_SAMPLES=$(TRAIN_SAMPLES) \
		-e VAL_SAMPLES=$(VAL_SAMPLES) \
		-e TEST_SAMPLES=$(TEST_SAMPLES) \
		-e OUTPUT_DIR=$(OUTPUT_DIR) \
		-e IDLE_AFTER=0 \
		$(DOCKER_IMAGE):$(IMAGE_TAG)

docker-ci-train: ## CI: download dataset from R2 and train (no TTY, no GPU). Mirror of docker-run-train for CI/scripts.
	@if [ -z "$(R2_DATASET_PATH)" ]; then echo "ERROR: R2_DATASET_PATH is required. e.g. make docker-ci-train R2_DATASET_PATH=runs/surge_simple/<sha>"; exit 1; fi
	docker run --rm --init \
		$(_INTERNAL_RUN_FLAGS) $(DOCKER_RUN_FLAGS) \
		-e MODE=train \
		-e PARAM_SPEC=$(PARAM_SPEC) \
		-e R2_DATASET_PATH=$(R2_DATASET_PATH) \
		-e OUTPUT_DIR=$(OUTPUT_DIR) \
		-e TRAIN_ARGS="$(TRAIN_ARGS)" \
		-e IDLE_AFTER=0 \
		$(DOCKER_IMAGE):$(IMAGE_TAG)

docker-ci-finalize: ## CI: finalize shards (no TTY, no GPU). Mirror of docker-run-finalize for CI/scripts.
	@if [ -z "$(R2_PREFIX)" ]; then echo "ERROR: R2_PREFIX is required. e.g. make docker-ci-finalize R2_PREFIX=runs/surge_simple/batch42"; exit 1; fi
	docker run --rm --init \
		$(_INTERNAL_RUN_FLAGS) $(DOCKER_RUN_FLAGS) \
		-e MODE=finalize-shards \
		-e R2_PREFIX=$(R2_PREFIX) \
		-e OUTPUT_DIR=$(OUTPUT_DIR) \
		-e VAL_SHARDS=$(VAL_SHARDS) \
		-e TEST_SHARDS=$(TEST_SHARDS) \
		-e IDLE_AFTER=0 \
		$(DOCKER_IMAGE):$(IMAGE_TAG)

# =====================================================================
# RunPod targets — launch massively parallel shard generation
#
# Requires:
#   pip install runpod click
#   export RUNPOD_API_KEY=<your-key>
#
# Quick-start:
#   make runpod-launch-dry-run RUNPOD_IMAGE=tinaudio/perm:dev-snapshot-<sha>
#   make runpod-launch RUNPOD_IMAGE=tinaudio/perm:dev-snapshot-<sha>
#   make runpod-stop RUN_ID=<run-id>
# =====================================================================
RUNPOD_NUM_PODS       ?= 10
RUNPOD_SHARDS_PER_POD ?= 10
RUNPOD_SHARD_SIZE     ?= 10000
RUNPOD_GPU_TYPE       ?= NVIDIA RTX A5000
RUNPOD_CLOUD_TYPE     ?= COMMUNITY
RUNPOD_IMAGE          ?= $(DOCKER_IMAGE):$(IMAGE_TAG)
RUN_ID                ?=

runpod-launch: ## Launch N RunPod pods for parallel shard generation
	python scripts/runpod_launch.py \
		--num-pods $(RUNPOD_NUM_PODS) \
		--shards-per-pod $(RUNPOD_SHARDS_PER_POD) \
		--shard-size $(RUNPOD_SHARD_SIZE) \
		--image $(RUNPOD_IMAGE) \
		--gpu-type "$(RUNPOD_GPU_TYPE)" \
		--cloud-type $(RUNPOD_CLOUD_TYPE) \
		--param-spec $(PARAM_SPEC)

runpod-launch-dry-run: ## Dry run: show what would be launched without creating pods
	python scripts/runpod_launch.py \
		--num-pods $(RUNPOD_NUM_PODS) \
		--shards-per-pod $(RUNPOD_SHARDS_PER_POD) \
		--shard-size $(RUNPOD_SHARD_SIZE) \
		--image $(RUNPOD_IMAGE) \
		--gpu-type "$(RUNPOD_GPU_TYPE)" \
		--cloud-type $(RUNPOD_CLOUD_TYPE) \
		--param-spec $(PARAM_SPEC) \
		--dry-run

runpod-stop: ## Stop all RunPod pods for a given run (requires RUN_ID)
	@if [ -z "$(RUN_ID)" ]; then echo "ERROR: RUN_ID is required. e.g. make runpod-stop RUN_ID=20260310-143022-a3f2b1"; exit 1; fi
	python scripts/runpod_stop.py --run-id $(RUN_ID)
