MAKEFLAGS += --warn-undefined-variables

help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

format: ## Run pre-commit hooks
	pre-commit run -a

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

test: ## Run quick tests (excludes slow, requires_vst)
	pytest -n auto -m "not slow and not requires_vst"

# test-full runs serially: GPU and DDP tests require exclusive device access
test-full: ## Run all tests
	pytest

test-bats: ## Run BATS shell tests
	bats --recursive tests/

install: ## Install project in editable mode with dev deps
	pip install uv
	uv pip install -r requirements.txt -e .

# coverage runs serially (no -n auto): GPU tests require exclusive device
# access and VRAM contention causes flaky failures with xdist parallelism.
coverage: ## Run tests with coverage report
	pip install uv
	uv pip install pytest-cov[toml]
	pytest --cov=src --cov-report=term-missing --cov-report=html -m "not slow"

benchmark: ## Run performance benchmarks
	pytest --benchmark-only -m "benchmark" -v

mutmut: ## Run mutation testing
	mutmut run

train: ## Train the model
	python src/train.py

# =====================================================================
# Docker targets
# =====================================================================
#
# Build mode:
#   docker-build-dev-snapshot — self-contained image. Clones the public
#                               repo at GIT_REF and bakes source + deps +
#                               Surge XT. Runs anywhere (CI, cloud, vast.ai).
#
# Required variables (pass on the command line):
#   GIT_REF             Git ref to bake. Used twice by the Dockerfile: the
#                       `synth-setter-src` stage downloads a GitHub tarball
#                       at this ref, and the `dev-snapshot` stage runs
#                       `git checkout --detach "${SYNTH_PERMUTATIONS_GIT_REF}"`
#                       after `git fetch origin`. A full 40-char SHA reachable
#                       from a pushed branch/tag satisfies both and pins the
#                       build deterministically. Since the repo is public,
#                       no credentials are needed for either fetch.
#                       (The CI workflow's `git_ref` input is different: it
#                       checks out locally and resolves any ref to a SHA via
#                       `git rev-parse HEAD` before the build.)
#
# Optional overrides:
#   DOCKER_FILE         Path to Dockerfile          (default: docker/ubuntu22_04/Dockerfile)
#   DOCKER_IMAGE        Image name                  (default: synth-setter)
#   DOCKER_BUILD_MODE   "source" or "prebuilt"       (default: prebuilt)
#   DOCKER_TARGETPLATFORM   "linux/amd64" or "linux/arm64" (default: linux/amd64)
#   DOCKER_TORCH_BACKEND  PyTorch backend (e.g. cu128, cpu) (default: cu128)
#   DOCKER_BUILD_FLAGS  Extra flags passed verbatim to docker buildx build.
# =====================================================================
DOCKER_FILE       ?= docker/ubuntu22_04/Dockerfile
DOCKER_IMAGE      ?= synth-setter
DOCKER_BASE_IMAGE ?= ubuntu@sha256:3ba65aa20f86a0fad9df2b2c259c613df006b2e6d0bfcc8a146afb8c525a9751
DOCKER_BASE_IMAGE_TAG ?= ubuntu22_04
DOCKER_BUILD_MODE ?= prebuilt
DOCKER_TARGETPLATFORM ?= linux/amd64
TARGETARCH ?= amd64
DOCKER_TORCH_BACKEND ?= cu128
DOCKER_BUILD_FLAGS ?=
_INTERNAL_BUILD_FLAGS :=
CURRENT_LOCAL_GIT_REF := $(strip $(shell git rev-parse HEAD))

docker-build-dev-snapshot: ## Build self-contained image (requires GIT_REF)
	@if [ -z "$(GIT_REF)" ]; then echo "ERROR: GIT_REF is required."; exit 1; fi
	DOCKER_BUILDKIT=1 docker buildx build \
		-f $(DOCKER_FILE) \
		$(_INTERNAL_BUILD_FLAGS) $(DOCKER_BUILD_FLAGS) \
		--platform $(DOCKER_TARGETPLATFORM) \
		--build-arg IMAGE="dev-snapshot" \
		--build-arg BUILD_MODE=$(DOCKER_BUILD_MODE) \
		--build-arg BASE_IMAGE=$(DOCKER_BASE_IMAGE) \
		--build-arg SYNTH_PERMUTATIONS_GIT_REF=$(GIT_REF) \
		--build-arg TORCH_BACKEND=$(DOCKER_TORCH_BACKEND) \
		--build-arg TARGETARCH=$(TARGETARCH) \
		--label org.opencontainers.image.base.name=$(DOCKER_BASE_IMAGE) \
		-t $(DOCKER_IMAGE):$(DOCKER_BASE_IMAGE_TAG)-dev-snapshot-$(GIT_REF) \
		-t $(DOCKER_IMAGE):dev-snapshot \
		.
