MAKEFLAGS += --warn-undefined-variables

help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

format: ## Run pre-commit hooks
	./.venv/bin/pre-commit run -a

install-git-hooks: ## Install commit and push enforcement hooks
	@common_dir=$$(git rev-parse --git-common-dir); \
	primary_root=$$(cd "$$common_dir/.." && pwd); \
	uv run --project "$$primary_root" pre-commit install --hook-type pre-commit --hook-type commit-msg --hook-type pre-push

GATE ?=
count-doc-noqa: ## Count inline `# noqa: DOC*` under src/ + tests/. Use GATE=1 to fail if non-zero.
	@scripts/ci/count_doc_noqa.sh $(if $(GATE),--gate,)

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

# Auto-prepend the Linux VST3 headless wrapper (Xvfb + xsettingsd + dbus) to
# every target that runs requires_vst tests. macOS has a real display server,
# so HEADLESS_WRAPPER is empty there. Wrapper exits cleanly even if no VST
# tests run (VST3-not-installed → tests skip via existing skipif decorators).
UNAME_S := $(shell uname -s)
HEADLESS_WRAPPER := $(if $(filter Linux,$(UNAME_S)),src/synth_setter/scripts/run-linux-vst-headless.sh,)
PYTEST := ./.venv/bin/pytest
# One BLAS/OpenMP thread per xdist worker: N workers each defaulting to a
# full-core intra-op pool oversubscribes the host N-fold (#2274). Env form
# (not torch.set_num_threads) so spawned DataLoader children inherit it.
XDIST_THREAD_CAPS := OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1

# Explicit paths avoid importing the entire medium suite during the inner loop.
FAST_TEST_BUDGET_SECONDS := 120
FAST_TEST_PATHS := tests/data/vst tests/evaluation tests/features tests/models tests/pipeline/ci_config tests/pipeline/configs tests/pipeline/schemas tests/schemas

# Wall-clock budgets per lane (enforced by tests/conftest.py, #2274): a run that
# blows its budget fails even when every test passes.
fast-test-budget: ## Print the fast-tier wall-clock budget in seconds.
	@printf '%s\n' '$(FAST_TEST_BUDGET_SECONDS)'

test-fast: ## Strict inner loop: curated CPU-only tests with a two-minute budget.
	PATH="$$(pwd)/.venv/bin:$$PATH" \
	  PYTEST_SESSION_BUDGET_SECONDS=$(FAST_TEST_BUDGET_SECONDS) \
	  $(XDIST_THREAD_CAPS) \
	  $(PYTEST) -n auto \
	  -m "not slow and not gpu and not mps and not requires_vst and not infra" \
	  $(FAST_TEST_PATHS)

test-medium: ## Complete CPU-only non-slow suite.
	PATH="$$(pwd)/.venv/bin:$$PATH" PYTEST_SESSION_BUDGET_SECONDS=600 $(XDIST_THREAD_CAPS) $(PYTEST) -n auto -m "not slow and not gpu and not mps and not requires_vst"

# Darwin VST editors share AppKit state, so requires_vst tests stay serial.
# GPU/MPS tests run serially because accelerators need exclusive access.
test-full-cpu: ## All non-hardware tests (slow + requires_vst included; gpu/mps excluded). Linux: bootstraps Xvfb; Darwin: serial VST lane.
	@if [ "$(UNAME_S)" = "Darwin" ]; then \
		status=0; \
		$(XDIST_THREAD_CAPS) $(PYTEST) -n auto -m "not gpu and not mps and not requires_vst" || status=1; \
		$(PYTEST) -m "requires_vst and not gpu and not mps" || status=1; \
		exit $$status; \
	else \
		$(XDIST_THREAD_CAPS) $(HEADLESS_WRAPPER) $(PYTEST) -n auto -m "not gpu and not mps"; \
	fi

test-full-gpu: ## GPU + CPU tests (mps excluded). Runs serially for exclusive GPU access. Linux: bootstraps Xvfb.
	$(HEADLESS_WRAPPER) pytest -m "not mps"

test-full-mps: ## MPS + CPU tests (gpu excluded). Runs serially for exclusive MPS access. (macOS Apple Silicon only.)
	@OS=$$(uname -s); ARCH=$$(uname -m); \
	if [ "$$OS" != "Darwin" ] || [ "$$ARCH" != "arm64" ]; then \
		echo "ERROR: test-full-mps requires macOS Apple Silicon (Darwin/arm64). Detected: $$OS/$$ARCH"; \
		exit 1; \
	fi
	pytest -m "not gpu"

test-vst-cpu: ## VST tests only (slow included; gpu/mps excluded). Linux: bootstraps Xvfb.
	$(HEADLESS_WRAPPER) pytest -m "requires_vst and not gpu and not mps"

# No marker deselection: this is the exhaustive lane for the sound-match
# bridge (#1787) — slow, requires_vst, and subprocess contract tests all run.
test-bridge: ## Sound-match bridge suite, exhaustive (slow + VST included). Linux: bootstraps Xvfb.
	$(HEADLESS_WRAPPER) pytest tests/test_predict_capture.py tests/data/vst/test_clap_map.py tests/data/vst/test_param_map.py tests/data/vst/test_param_map_completeness.py tests/data/vst/test_clap_introspect.py tests/tools/test_build_param_map.py -v

# --confcutdir avoids loading tests/conftest.py (torch/h5py/Hydra imports),
# so this target works on a minimal host with only the stdlib + pytest.
test-infra: ## Devcontainer + GHA invariant tests — stdlib-only, no torch/Hydra.
	pytest tests/infra/ --confcutdir=tests/infra

codex-doctor: ## Check Codex CLI, repo skill projection, and tinaudio skill plugin discovery.
	scripts/dev/codex-doctor.sh

# Single source of truth for the marker expressions CI runs (see #1353): the
# workflows call these instead of re-spelling pytest, so the filters can't drift.

# `--cov=scripts/ci` is needed alongside `--cov=src`: pytest-cov's `--cov`
# overrides [tool.coverage.run].source in pyproject.toml.
CI_COV := --cov=src --cov=scripts/ci --cov-branch --cov-report=xml --cov-report=term

test-ci-unit: ## CI medium suite (test.yml): CPU-only, excludes slow/gpu/mps.
	PYTEST_SESSION_BUDGET_SECONDS=1500 uv run pytest -n auto -m "not slow and not gpu and not mps" -vv -s $(CI_COV)

test-ci-slow: ## CI slow suite (cpu-slow.yml): slow CPU tests with live R2, excludes gpu/mps/vst.
	PYTEST_SESSION_BUDGET_SECONDS=4500 uv run pytest -vv -s -m "slow and not gpu and not mps and not requires_vst" $(CI_COV)

test-ci-slow-pr: ## CI slow PR suite (cpu-slow.yml): slow CPU tests without live R2.
	PYTEST_SESSION_BUDGET_SECONDS=4500 uv run pytest -vv -s -m "slow and not gpu and not mps and not requires_vst and not integration_r2" $(CI_COV)

test-ci-nightly: ## CI nightly suite (nightly.yml): all non-hardware, non-VST (unit + slow).
	PYTEST_SESSION_BUDGET_SECONDS=4800 uv run pytest -vv -s -m "not gpu and not mps and not requires_vst"

# Local mirror of .github/workflows/deflake-mps.yml — see that workflow for the rationale on each flag.
# `pipefail` (target-scoped via bash) ensures pytest's non-zero exit propagates through `tee`.
deflake: SHELL := /bin/bash
deflake: ## Rerun TEST COUNT times; retain failed tmp_paths under deflake-artifacts/
	@test -n "$(TEST)" || (echo "usage: make deflake TEST=<node-id> [COUNT=50]" >&2; exit 1)
	@set -o pipefail; \
	mkdir -p deflake-artifacts && \
	pytest \
	  --count="$(or $(COUNT),50)" \
	  -vv -s \
	  -o tmp_path_retention_policy=failed \
	  --basetemp "$(CURDIR)/deflake-artifacts/pytest" \
	  --junitxml deflake-artifacts/junit.xml \
	  -- "$(TEST)" 2>&1 | tee deflake-artifacts/pytest.log

install: SHELL := /bin/bash
install: ## End-to-end: install uv, create .venv (Python 3.12), install deps, set up pre-commit
	@set -euo pipefail; \
	UV=$$(command -v uv 2>/dev/null || echo "$$HOME/.local/bin/uv"); \
	if ! { [[ -x "$$UV" ]] && [[ "$$("$$UV" --version | awk '{print $$2}')" == "0.11.28" ]]; } && \
		! { [[ -x "$$HOME/.local/bin/uv" ]] && [[ "$$("$$HOME/.local/bin/uv" --version | awk '{print $$2}')" == "0.11.28" ]]; }; then \
		echo "Installing uv..."; curl -LsSf https://astral.sh/uv/0.11.28/install.sh | sh; \
	fi; \
	UV=$$(command -v uv 2>/dev/null || echo "$$HOME/.local/bin/uv"); \
	[[ "$$("$$UV" --version 2>/dev/null | awk '{print $$2}')" == "0.11.28" ]] || UV="$$HOME/.local/bin/uv"; \
	{ [[ -x "$$UV" ]] && [[ "$$("$$UV" --version | awk '{print $$2}')" == "0.11.28" ]]; } || { echo "ERROR: uv 0.11.28 required"; exit 1; }; \
	if [[ -d .venv ]]; then \
		PY_VER=$$(.venv/bin/python -c "import sys; print('.'.join(map(str, sys.version_info[:3])))" 2>/dev/null); \
		[[ "$$PY_VER" == "3.12.13" ]] || { echo "ERROR: existing .venv has Python $$PY_VER, need 3.12.13 (rm -rf .venv to recreate)"; exit 1; }; \
	else \
		"$$UV" venv --python 3.12.13 --prompt synth-setter .venv; \
	fi; \
	"$$UV" pip install --python .venv/bin/python --group dev -e .
	@if [[ -n "$$(git config --get core.hooksPath 2>/dev/null)" ]]; then \
		echo "Skipping Git hook installation because core.hooksPath is set."; \
	else \
		$(MAKE) install-git-hooks; \
	fi
	@echo ""
	@echo "Next: source .venv/bin/activate"

STUDIORACK := uv run synth-setter-plugins

install-studiorack: ## Install the pinned Studiorack CLI and its locked dependencies
	npm ci

install-surge-xt: install-studiorack ## Install pinned Surge XT through Studiorack
	$(STUDIORACK) install --plugin surge-synthesizer/surge

install-cardinal: install-studiorack ## Install pinned Cardinal through its optional Studiorack manifest
	$(STUDIORACK) --manifest studiorack-cardinal.json install --plugin distrho/cardinal

install-dexed: install-studiorack ## Install pinned Dexed through Studiorack
	$(STUDIORACK) install --plugin asb2m10/dexed

install-obxf: install-studiorack ## Install pinned OB-Xf through Studiorack
	$(STUDIORACK) install --plugin surge-synthesizer/ob-xf

install-six-sines: install-studiorack ## Install pinned Six Sines through Studiorack
	$(STUDIORACK) install --plugin baconpaul/six-sines

install-ultramaster-kr106: install-studiorack ## Install pinned Ultramaster KR-106 through Studiorack
	$(STUDIORACK) install --plugin kayrockscreenprinting/ultramaster-kr106

install-plugins: install-studiorack ## Install every VST3 pinned in studiorack.json
	$(STUDIORACK) install

link-plugins: SHELL := /bin/bash
link-plugins: ## Link installed Studiorack packages into the checkout's plugins/ namespace
	@set -e; \
	primary="$$(cd "$$(dirname "$$(git rev-parse --git-common-dir)")" && pwd)"; \
	here="$$(git rev-parse --show-toplevel)"; \
	central="$$primary/plugins"; \
	if [[ "$$primary" != "$$here" && -L "$$here/plugins" && "$$(readlink "$$here/plugins")" == "$$central" ]]; then \
		[[ -d "$$central" ]] || { echo "ERROR: primary plugins directory is unavailable: $$central" >&2; exit 1; }; \
		echo "plugins/ already linked -> $$central"; \
	elif [[ "$$primary" != "$$here" && -d "$$central" && ! -e "$$here/plugins" && ! -L "$$here/plugins" ]]; then \
		ln -s "$$central" "$$here/plugins"; \
		echo "plugins/ linked -> $$central"; \
	else \
		$(STUDIORACK) link; \
		$(STUDIORACK) --manifest studiorack-cardinal.json link; \
	fi

# Symlink this worktree's gitignored thoughts/ to the primary's central thoughts/
# so qrspi docs from every worktree converge; migrates pre-existing files first.
link-thoughts: ## Symlink this worktree's thoughts/ to the primary checkout's central thoughts/ (no-op in primary)
	@set -e; \
	primary="$$(cd "$$(dirname "$$(git rev-parse --git-common-dir)")" && pwd)"; \
	here="$$(git rev-parse --show-toplevel)"; \
	if [ "$$primary" = "$$here" ]; then \
		echo "In primary checkout — thoughts/ is already central."; exit 0; \
	fi; \
	central="$$primary/thoughts"; \
	mkdir -p "$$central"; \
	if [ -L "$$here/thoughts" ]; then \
		if [ "$$(readlink "$$here/thoughts")" = "$$central" ]; then \
			echo "thoughts/ already linked -> $$central"; exit 0; \
		fi; \
		rm -f "$$here/thoughts"; \
	fi; \
	if [ -d "$$here/thoughts" ]; then \
		list="$$(mktemp)"; \
		find "$$here/thoughts" -type f > "$$list" || { rm -f "$$list"; exit 1; }; \
		while IFS= read -r f; do \
			rel="$${f#"$$here/thoughts/"}"; \
			if [ -e "$$central/$$rel" ]; then \
				if ! cmp -s "$$f" "$$central/$$rel"; then \
					alt="$$rel.from-$$(basename "$$here")"; \
					cp "$$f" "$$central/$$alt" || exit 1; \
					echo "collision: kept central/$$rel; saved worktree copy as $$alt"; \
				fi; \
			else \
				mkdir -p "$$central/$$(dirname "$$rel")" || exit 1; \
				cp "$$f" "$$central/$$rel" || exit 1; \
				echo "migrated $$rel"; \
			fi; \
		done < "$$list"; \
		rm -f "$$list"; \
		rm -rf "$$here/thoughts"; \
	fi; \
	ln -sfn "$$central" "$$here/thoughts"; \
	echo "linked thoughts/ -> $$central"

link-skills: ## Project the installed skills marketplace into ~/.agents/skills for Gemini/Antigravity discovery
	@scripts/dev/link-skills.sh

# Mirrors the --cov flags used by .github/workflows/test.yml so local
# coverage runs reproduce CI output (xml report feeds Codecov; html is for
# local browsing).
coverage: ## Run tests with coverage report
	pytest --cov=src --cov-branch --cov-report=xml --cov-report=term-missing --cov-report=html -m "not slow and not gpu and not mps"

benchmark: ## Run performance benchmarks
	pytest --benchmark-only -m "benchmark" -v

mutmut: ## Run mutation testing
	OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES mutmut run

train: ## Train the model
	python src/train.py

# All vars are expensive — enable only while actively reproducing a crash.
# CUDA_LAUNCH_BLOCKING serialises kernel launches so tracebacks name the offending kernel.
export-debug-envars: ## Print CUDA/PyTorch debug export commands (eval $(make export-debug-envars))
	@echo "export CUDA_LAUNCH_BLOCKING=1;"
	@echo "export TORCH_SHOW_CPP_STACKTRACES=1;"
	@echo "export TORCH_DISTRIBUTED_DEBUG=DETAIL;"
	@echo "export NCCL_DEBUG=INFO;"
	@echo "export TORCH_LOGS=all;"
	@echo "export TORCHDYNAMO_VERBOSE=1;"

unset-debug-envars: ## Print unset commands to clear CUDA/PyTorch debug variables (eval $(make unset-debug-envars))
	@echo "unset CUDA_LAUNCH_BLOCKING;"
	@echo "unset TORCH_SHOW_CPP_STACKTRACES;"
	@echo "unset TORCH_DISTRIBUTED_DEBUG;"
	@echo "unset NCCL_DEBUG;"
	@echo "unset TORCH_LOGS;"
	@echo "unset TORCHDYNAMO_VERBOSE;"

# =====================================================================
# Docker targets
# =====================================================================
#
# Build mode:
#   docker-build-dev-snapshot — self-contained image. Clones the public
#                               repo at GIT_REF and bakes source + deps +
#                               Surge XT. Runs anywhere (CI, cloud, vast.ai).
#
# Required variables (pass on the command line):
#   GIT_REF             Git ref to bake. Used twice by the Dockerfile: the
#                       `synth-setter-src` stage downloads a GitHub tarball
#                       at this ref, and the `dev-snapshot` stage runs
#                       `git checkout --detach "${SYNTH_PERMUTATIONS_GIT_REF}"`
#                       after `git fetch origin`. A full 40-char SHA reachable
#                       from a pushed branch/tag satisfies both and pins the
#                       build deterministically. Since the repo is public,
#                       no credentials are needed for either fetch.
#                       (The CI workflow's `git_ref` input is different: it
#                       checks out locally and resolves any ref to a SHA via
#                       `git rev-parse HEAD` before the build.)
#
# Optional overrides:
#   DOCKER_FILE         Path to Dockerfile          (default: docker/ubuntu22_04/Dockerfile)
#   DOCKER_IMAGE        Image name                  (default: synth-setter)
#   DOCKER_BUILD_MODE   "source" or "prebuilt"       (default: prebuilt)
#   DOCKER_TARGETPLATFORM   "linux/amd64" or "linux/arm64" (default: linux/amd64)
#   DOCKER_TORCH_BACKEND  PyTorch backend (e.g. cu128, cpu) (default: cu128)
#   DOCKER_BUILD_FLAGS  Extra flags passed verbatim to docker buildx build.
# =====================================================================
DOCKER_FILE       ?= docker/ubuntu22_04/Dockerfile
DOCKER_IMAGE      ?= synth-setter
DOCKER_BASE_IMAGE ?= ubuntu@sha256:3ba65aa20f86a0fad9df2b2c259c613df006b2e6d0bfcc8a146afb8c525a9751
DOCKER_BASE_IMAGE_TAG ?= ubuntu22_04
DOCKER_BUILD_MODE ?= prebuilt
DOCKER_TARGETPLATFORM ?= linux/amd64
TARGETARCH ?= amd64
DOCKER_TORCH_BACKEND ?= cu128
DOCKER_BUILD_FLAGS ?=
_INTERNAL_BUILD_FLAGS :=
CURRENT_LOCAL_GIT_REF = $(strip $(shell git rev-parse HEAD))

docker-build-dev-snapshot: ## Build self-contained image (requires GIT_REF)
	@if [ -z "$(GIT_REF)" ]; then echo "ERROR: GIT_REF is required."; exit 1; fi
	DOCKER_BUILDKIT=1 docker buildx build \
		-f $(DOCKER_FILE) \
		$(_INTERNAL_BUILD_FLAGS) $(DOCKER_BUILD_FLAGS) \
		--platform $(DOCKER_TARGETPLATFORM) \
		--build-arg BUILD_MODE=$(DOCKER_BUILD_MODE) \
		--build-arg BASE_IMAGE=$(DOCKER_BASE_IMAGE) \
		--build-arg SYNTH_PERMUTATIONS_GIT_REF=$(GIT_REF) \
		--build-arg TORCH_BACKEND=$(DOCKER_TORCH_BACKEND) \
		--build-arg TARGETARCH=$(TARGETARCH) \
        --target dev-snapshot \
		--label org.opencontainers.image.base.name=$(DOCKER_BASE_IMAGE) \
		-t $(DOCKER_IMAGE):$(DOCKER_BASE_IMAGE_TAG)-dev-snapshot-$(GIT_REF) \
		-t $(DOCKER_IMAGE):dev-snapshot \
		.

docker-build-devcontainer-tools: ## Build devcontainer-tools image
	@if [ -z "$(GIT_REF)" ]; then echo "ERROR: GIT_REF is required."; exit 1; fi
	DOCKER_BUILDKIT=1 docker buildx build \
		-f $(DOCKER_FILE) \
		$(_INTERNAL_BUILD_FLAGS) $(DOCKER_BUILD_FLAGS) \
		--platform $(DOCKER_TARGETPLATFORM) \
		--build-arg BUILD_MODE=$(DOCKER_BUILD_MODE) \
		--build-arg BASE_IMAGE=$(DOCKER_BASE_IMAGE) \
		--build-arg SYNTH_PERMUTATIONS_GIT_REF=$(GIT_REF) \
		--build-arg TORCH_BACKEND=$(DOCKER_TORCH_BACKEND) \
		--build-arg TARGETARCH=$(TARGETARCH) \
		--target devcontainer-tools \
		-t $(DOCKER_IMAGE):devcontainer-tools \
		.

docker-build-devcontainer-tools-dev-user: ## Build non-root devcontainer-tools-dev-user image
	@if [ -z "$(GIT_REF)" ]; then echo "ERROR: GIT_REF is required."; exit 1; fi
	DOCKER_BUILDKIT=1 docker buildx build \
		-f $(DOCKER_FILE) \
		$(_INTERNAL_BUILD_FLAGS) $(DOCKER_BUILD_FLAGS) \
		--platform $(DOCKER_TARGETPLATFORM) \
		--build-arg BUILD_MODE=$(DOCKER_BUILD_MODE) \
		--build-arg BASE_IMAGE=$(DOCKER_BASE_IMAGE) \
		--build-arg SYNTH_PERMUTATIONS_GIT_REF=$(GIT_REF) \
		--build-arg TORCH_BACKEND=$(DOCKER_TORCH_BACKEND) \
		--build-arg TARGETARCH=$(TARGETARCH) \
		--target devcontainer-tools-dev-user \
		-t $(DOCKER_IMAGE):devcontainer-tools-dev-user \
		.
