defaults:
  - encoder: cnn
  - _self_

_target_: synth_setter.models.ksin_flow_matching_module.KSinFlowMatchingModule

scheduler: null

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-4
  weight_decay: 0.0

vector_field:
  _target_: synth_setter.models.components.transformer.ApproxEquivTransformer
  projection:
    _target_: synth_setter.models.components.transformer.LearntProjection
    d_model: ${model.vector_field.d_model}
    d_token: ${model.vector_field.d_model}
    num_params: ${mul:${data.k},2}
    num_tokens: ${data.k}
    initial_ffn: true
    final_ffn: false
  num_layers: 5
  d_model: 128
  conditioning_dim: ${model.encoder.out_dim}
  num_heads: 4
  d_ff: 256
  num_tokens: ${model.vector_field.projection.num_tokens}
  learn_pe: false
  learn_projection: true
  pe_type: none
  pe_penalty: 0.0
  time_encoding: scalar
  projection_penalty: 0.01
  norm: layer
  skip_first_norm: false
  adaln_mode: basic
  zero_init: false
  outer_residual: false

# training
cfg_dropout_rate: 0.1

p_time: uniform
w_time: none

coupling: uniform
oversample_ot: 1.0

probability_path: rectified

cfm_sigma: 0.0
fm_sigma: 0.0
rectified_sigma_min: 0.0

# sampling
sample_schedule: linear
validation_sample_steps: 50
validation_cfg_strength: 2.0
test_sample_steps: 200
test_cfg_strength: 2.0

# SYMMETRY DISCOVERY!
freeze_for_first_n_steps: 0

# compile model for faster training with pytorch 2.0
compile: true
