defaults:
  - _self_

_target_: synth_setter.models.surge_ff_module.SurgeFeedForwardModule

net:
  _target_: synth_setter.models.components.transformer.ASTWithProjectionHead
  d_model: 768
  d_out: 92
  n_heads: 16
  n_layers: 12
  patch_size: 16
  patch_stride: 10
  input_channels: 2
  spec_shape: [128, 401]

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: ${trainer.max_steps}
  eta_min: ${mul:${model.optimizer.lr},1e-2}

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-4
  weight_decay: 0.0

# compile model for faster training with pytorch 2.0
compile: true
