_target_: synth_setter.data.fm_datamodule.FMDataModule
algorithm: mixed
signal_length: 1024
break_symmetry: false
train_val_test_sizes:
  - 409_600_000
  - 10_240
  - 51_200
train_val_test_seeds: [123, 456, 789]
batch_size: 1024
num_workers: 8
ot: false
