_target_: synth_setter.data.ksin_datamodule.KSinDataModule
k: 1
signal_length: 1024
sort_frequencies: false
break_symmetry: false
shift_test_distribution: true
train_val_test_sizes: [1_024_000, 50_000, 50_000]
batch_size: 1024
