_target_: synth_setter.data.torchsynth_datamodule.TorchSynthDataModule
sample_rate: 44_100
signal_length: 4_410
midi_pitch: 60
num_params: 76
train_val_test_sizes: [100_000, 10_000, 10_000]
train_val_test_seeds: [123, 456, 789]
batch_size: 32
num_workers: 4
