param_spec: surge_simple
plugin_path: plugins/Surge XT.vst3
output_format: hdf5
sample_rate: 16000
shard_size: 10000
num_shards: 48
base_seed: 42

splits:
  train: 44
  val: 2
  test: 2

preset_path: presets/surge-base.vstpreset
channels: 2
velocity: 100
signal_duration_seconds: 4.0
min_loudness: -55.0
sample_batch_size: 32
