"""Canonical procedural source contracts for pyFDN."""

import hashlib

import numpy as np
import pytest

import synth_setter.data.pyfdn_source as pyfdn_source
from synth_setter.data.pyfdn_source import (
    canonical_pyfdn_source_provenance,
    generate_canonical_pyfdn_source,
)


def test_generate_canonical_pyfdn_source_has_exact_waveform_contract() -> None:
    """The canonical source is finite contiguous channel-first float32 audio."""
    source = generate_canonical_pyfdn_source()

    assert source.shape == (1, 176_400)
    assert source.dtype == np.float32
    assert source.flags.c_contiguous
    assert np.isfinite(source).all()
    assert not source.flags.writeable
    with pytest.raises(ValueError, match="cannot set WRITEABLE flag"):
        source.setflags(write=True)
    assert np.any(source[0, :44_100] != 0.0)
    np.testing.assert_array_equal(source[0, 44_100:], np.zeros(132_300, dtype=np.float32))


def test_generate_canonical_pyfdn_source_uses_exact_librosa_chirp_call(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Generation fixes every librosa sweep argument and retains its default phase.

    :param monkeypatch: Scoped librosa chirp replacement.
    """
    received: dict[str, object] = {}

    def chirp(**kwargs: object) -> np.ndarray:
        received.update(kwargs)
        return np.ones(44_100, dtype=np.float64)

    monkeypatch.setattr(pyfdn_source.librosa, "chirp", chirp)
    monkeypatch.setattr(
        pyfdn_source,
        "PYFDN_CANONICAL_SOURCE_SHA256",
        "ae5c41d9d29ac976049f6b1c3d59c3a02fa963a62f0e36866b679d89cf49b076",
    )

    source = generate_canonical_pyfdn_source()

    assert received == {
        "fmin": 20.0,
        "fmax": 20_000.0,
        "sr": 44_100,
        "length": 44_100,
        "linear": False,
    }
    np.testing.assert_array_equal(source[0, :44_100], np.full(44_100, 0.1, np.float32))


def test_generate_canonical_pyfdn_source_nonfinite_chirp_raises(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Non-finite library output cannot become canonical source bytes.

    :param monkeypatch: Scoped invalid librosa chirp replacement.
    """
    invalid = np.zeros(44_100, dtype=np.float64)
    invalid[1] = np.nan
    monkeypatch.setattr(pyfdn_source.librosa, "chirp", lambda **_: invalid)

    with pytest.raises(ValueError, match="finite"):
        generate_canonical_pyfdn_source()


def test_generate_canonical_pyfdn_source_out_of_range_chirp_raises(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Library output above unit amplitude cannot violate the 0.1 source bound.

    :param monkeypatch: Scoped out-of-range librosa chirp replacement.
    """
    invalid = np.full(44_100, 1.01, dtype=np.float64)
    monkeypatch.setattr(pyfdn_source.librosa, "chirp", lambda **_: invalid)

    with pytest.raises(ValueError, match="amplitude"):
        generate_canonical_pyfdn_source()


def test_generate_canonical_pyfdn_source_has_bounded_near_zero_start() -> None:
    """Default librosa phase starts near zero and the excitation never exceeds 0.1."""
    excitation = generate_canonical_pyfdn_source()[0, :44_100]

    assert abs(float(excitation[0])) < 1e-7
    peak = np.max(np.abs(excitation))
    assert np.float32(0.09) < peak <= np.float32(0.1)


def test_generate_canonical_pyfdn_source_matches_representative_locked_samples() -> None:
    """Pinned samples detect phase or frequency-law drift without gating on a byte digest."""
    source = generate_canonical_pyfdn_source()

    np.testing.assert_allclose(
        source[0, [0, 1, 2, 11_025, 22_050, 33_075, 44_099]],
        np.array(
            [
                6.1232338e-18,
                2.8497365e-04,
                5.6998961e-04,
                6.5586314e-02,
                -8.5105821e-02,
                -1.9153437e-02,
                -3.2231044e-02,
            ],
            dtype=np.float32,
        ),
        rtol=0.0,
        atol=1e-7,
    )


def test_generate_canonical_pyfdn_source_repeated_calls_are_deterministic() -> None:
    """Repeated generation yields identical samples and byte fingerprints."""
    first = generate_canonical_pyfdn_source()
    second = generate_canonical_pyfdn_source()

    np.testing.assert_array_equal(second, first)
    assert hashlib.sha256(second.tobytes()).digest() == hashlib.sha256(
        first.tobytes()
    ).digest()
    assert not np.shares_memory(first, second)


def test_canonical_pyfdn_source_provenance_has_complete_source_spec() -> None:
    """Provenance records every sound-affecting field and the generated byte digest."""
    source = generate_canonical_pyfdn_source()

    provenance = canonical_pyfdn_source_provenance()

    assert provenance == {
        "identity": "librosa_log_chirp_v1",
        "implementation": "librosa.chirp",
        "fmin_hz": 20.0,
        "fmax_hz": 20_000.0,
        "sample_rate_hz": 44_100,
        "chirp_frames": 44_100,
        "total_frames": 176_400,
        "linear": False,
        "phi": None,
        "amplitude": 0.1,
        "tail_frames": 132_300,
        "channels": 1,
        "dtype": "float32",
        "layout": "channel_first",
        "librosa_version": "0.11.0",
        "sha256": hashlib.sha256(source.tobytes()).hexdigest(),
    }
